spring:
  profiles:
    active: local
    include:
      - jwt
      - api
<<<<<<< HEAD
      - oauth2
=======
      - mongoDB
>>>>>>> f4d118dabe2eff9b8cc1e788d4d1554b4b5d7013

  #  datasource:
  #    url: jdbc:postgresql://postgresql:5432/startrip
  #    username: postgres
  #    password: postgres

  hikari:
    maximum-pool-size: 4

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
      format_sql: true

  data:
    mongodb:
      url: mongodb://127.0.0.1:27017
      database: mongostartrip


logging:
  config: classpath:log4j2.yml
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
